storebackend_statics:
    resource: "@StoreBackendBundle/Resources/config/statics.yml"
    prefix:   /

storebackend_products:
    resource: "@StoreBackendBundle/Resources/config/modules/product.yml"
    prefix:   /products

storebackend_categories:
    resource: "@StoreBackendBundle/Resources/config/modules/category.yml"
    prefix:   /categories

storebackend_cms:
    resource: "@StoreBackendBundle/Resources/config/modules/cms.yml"
    #argument{_locale}pour traduire tout mon module cms au niveau du routing
    #Argument spécifique au routing reconnu par le système d'internationalisation
    prefix:   /{_locale}/cms
    requirements:
      _locale: en|fr|es

storebackend_suppliers:
     resource: "@StoreBackendBundle/Resources/config/modules/supplier.yml"
     prefix:   /suppliers

storebackend_sliders:
     resource: "@StoreBackendBundle/Resources/config/modules/slider.yml"
     prefix:   /sliders

storebackend_jeweler:
     resource: "@StoreBackendBundle/Resources/config/modules/jeweler.yml"
     prefix:   /jeweler

store_backend_index:
  path: /dashboard #uri de la route
  defaults: { _controller: StoreBackendBundle:Main:index }

  #permet de commander les actions du controller et de la vue

