storebackend_statics:
    resource: "@StoreBackendBundle/Resources/config/statics.yml"
    prefix:   /

storebackend_products:
    resource: "@StoreBackendBundle/Resources/config/modules/product.yml"
    prefix:   /products

storebackend_categories:
    resource: "@StoreBackendBundle/Resources/config/modules/category.yml"
    prefix:   /categories

storebackend_cms:
    resource: "@StoreBackendBundle/Resources/config/modules/cms.yml"
    prefix:   /cms

storebackend_suppliers:
     resource: "@StoreBackendBundle/Resources/config/modules/supplier.yml"
     prefix:   /suppliers

store_backend_index:
  path: /dashboard #uri de la route
  defaults: { _controller: StoreBackendBundle:Main:index }

  #permet de commander les actions du controller et de la vue

