#Page list of categories
store_backend_category_list:
    path:     /list
    defaults: { _controller: StoreBackendBundle:Category:list }

#Page view a category
store_backend_category_view:
    path: /view/{id}/{name}
    #id = argument nommé avec accolades : {id]
    defaults: { _controller: StoreBackendBundle:Category:view }
    requirements:
           id: \d+
           name: .+
           _method: GET


store_backend_category_remove:
     path: /remove/{id}
     defaults: { _controler: StoreBackendBundle:Category: remove }


store_backend_category_new:
      path:   /new
      defaults: { _controller: StoreBackendBundle:Category:new }