#Page list of cms
store_backend_cms_list:
    path: /list
    defaults: { _controller: StoreBackendBundle:CMS:list }

#Page view a product
store_backend_cms_view:
    path: /view/{id}
    defaults: { _controller: StoreBackendBundle:CMS:view }
    requirements:
      id: \d+
      _method: GET


store_backend_cms_remove:
     path: /remove/{id}
     defaults: { _controller: StoreBackendBundle:CMS:remove }

store_backend_cms_new:
      path:   /new
      defaults: { _controller: StoreBackendBundle:CMS:new }

store_backend_cms_edit:
      path:   /edit/{id}
      defaults: { _controller: StoreBackendBundle:CMS:edit }

store_backend_cms_activate:
      path:   /activate/{id}/{action}
      defaults: { _controller: StoreBackendBundle:CMS:activate }

store_backend_cms_state:
      path:   /state/{id}/{action}
      defaults: { _controller: StoreBackendBundle:CMS:state }