#Page list of products
store_backend_product_list:
    path:     /list
    defaults: { _controller: StoreBackendBundle:Product:list }

#Page view a product
store_backend_product_view:
    path:     /view/{id}/{name}
    defaults: { _controller: StoreBackendBundle:Product:view }
    requirements:
      id: \d+
      name: .+
      _method: GET

#page list of product
store_backend_product_remove:
     path:   /remove/{id}
     defaults: { _controller: StoreBackendBundle:Product:remove }



store_backend_product_new:
      path:   /new
      defaults: { _controller: StoreBackendBundle:Product:new }

store_backend_product_edit:
      path:   /edit/{id}
      defaults: { _controller: StoreBackendBundle:Product:edit }