#Page list of suppliers
store_backend_supplier_list:
    path: /list
    defaults: { _controller: StoreBackendBundle:Supplier:list }

#Page view a product
store_backend_supplier_view:
    path:     /view/{id}/{name}
    defaults: { _controller: StoreBackendBundle:Supplier:view }
    requirements:
      id: \d+
      name: .+
      _method: GET

store_backend_supplier_remove:
     path: /remove/{id}
     defaults: { _controller: StoreBackendBundle:Supplier: remove }
